-- =============================================
-- MULTI-AGENT AUTHENTICATION MIGRATION
-- Adds support for tracking which agent sends each message
-- =============================================

-- 1. Create agents table
CREATE TABLE IF NOT EXISTS agents (
    id SERIAL PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100),
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    last_login TIMESTAMP WITH TIME ZONE
);

-- 2. Add agent columns to messages table
ALTER TABLE messages ADD COLUMN IF NOT EXISTS agent_id INTEGER REFERENCES agents(id);
ALTER TABLE messages ADD COLUMN IF NOT EXISTS agent_name VARCHAR(100);

-- 3. Create index for faster agent lookups
CREATE INDEX IF NOT EXISTS idx_messages_agent ON messages(agent_id);

-- 4. Create default admin agent (password: admin123 - CHANGE IN PRODUCTION!)
-- Password hash is bcrypt of 'admin123'
INSERT INTO agents (username, password_hash, name, email) 
VALUES ('admin', '$2b$10$YourHashWillBeGeneratedByCode', 'Administrador', 'admin@example.com')
ON CONFLICT (username) DO NOTHING;

-- Note: The actual password hash will be generated by the backend when creating agents
