# Railway Configuration para Chatwoot + n8n + WhatsApp
# Documentación: https://docs.railway.app/reference/config-file

[build]
# Usar Nixpacks para detección automática de Node.js
builder = "nixpacks"
# Comando de build personalizado
buildCommand = "npm ci && npm run build"

[deploy]
# Comando para iniciar la aplicación en producción
startCommand = "npx serve -s build -l $PORT"
# Política de reinicio
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 3

# Variables de entorno por defecto
[env]
NODE_ENV = "production"
REACT_APP_VERSION = "1.0.0"
REACT_APP_RAILWAY_DEPLOY = "true"

# Configuración de red
[networking]
# Railway asignará automáticamente el puerto
# No necesitas especificar el puerto aquí

# Configuración de recursos (opcional)
[resources]
# Memoria en MB (Railway asignará automáticamente si no se especifica)
# memory = 512
# CPU en millicores (Railway asignará automáticamente si no se especifica)  
# cpu = 500

# Configuración de logs
[logging]
# Nivel de logs
level = "info"
# Formato de logs
format = "json"

# Health checks
[healthcheck]
# Endpoint para verificar salud de la aplicación
path = "/"
# Intervalo en segundos
interval = 30
# Timeout en segundos
timeout = 10
# Reintentos antes de marcar como unhealthy
retries = 3

# Configuración de dominio (opcional)
[domains]
# Railway generará automáticamente un subdominio
# También puedes configurar dominios personalizados aquí

# Configuración de servicios adicionales
[services]

  # Servicio principal (React App)
  [services.web]
  # Comando de build
  buildCommand = "npm ci && npm run build"
  # Comando de inicio
  startCommand = "npx serve -s build -l $PORT"
  
  # Variables de entorno específicas del servicio
  [services.web.env]
  NODE_ENV = "production"
  GENERATE_SOURCEMAP = "false"
  REACT_APP_BUILD_DATE = "$RAILWAY_GIT_COMMIT_SHA"

# Configuración de desarrollo (opcional)
[develop]
# Comando para desarrollo local
command = "npm start"
# Variables de entorno para desarrollo
[develop.env]
NODE_ENV = "development"
REACT_APP_DEV_MODE = "true"

# Configuración de Git (Railway la detecta automáticamente)
[git]
# Branch principal para deploys automáticos
branch = "main"
# Directorio raíz del proyecto
root = "."

# Configuración de notificaciones (opcional)
[notifications]
# Webhook para notificaciones de deploy
# webhookUrl = "https://your-webhook-url.com"

# Configuración de cache
[cache]
# Cachear node_modules entre builds
enabled = true
# Directorios a cachear
paths = ["node_modules", ".next/cache"]

# Configuración de seguridad
[security]
# Headers de seguridad automáticos
headers = true

# Configuración de SSL (Railway maneja esto automáticamente)
[ssl]
# Certificados automáticos
enabled = true

# Configuración de backup (opcional)
[backup]
# Backup automático de variables de entorno
enabled = true

# Configuración de monitoreo
[monitoring]
# Métricas automáticas
enabled = true
# Alertas por email (opcional)
# alerts = ["tu@email.com"]

# Configuración de staging (opcional)
[staging]
# Branch para staging
branch = "develop"
# Variables específicas de staging
[staging.env]
NODE_ENV = "staging"
REACT_APP_STAGING = "true"